# Generated by Django 4.1.2 on 2022-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=30)),
                ('Password1', models.CharField(max_length=20)),
                ('Password2', models.CharField(max_length=20)),
            ],
        ),
    ]
