# Generated by Django 4.1.2 on 2022-10-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('sr', models.IntegerField()),
                ('sb', models.CharField(max_length=10)),
                ('sc', models.BigIntegerField()),
            ],
        ),
    ]
